### ISSUE TITLE
Fails to build on Python 3.13 (numpy)

### ISSUE THREAD

**Issue by ErikBjare** [ErikBjare/gptme-rag#4]
```
$ pipx install gptme-rag
Fatal error from pip prevented installation. Full pip output in file:
    /Users/michael/.local/pipx/logs/cmd_2024-12-12_19.03.02_pip_errors.log

pip seemed to fail to build package:
    numpy<2.0.0

Some possibly relevant errors from pip install:
    error: subprocess-exited-with-error
    error: unknown target CPU 'armv8.2-a+fp16'
    /Library/Developer/CommandLineTools/usr/lib/clang/15.0.0/include/arm_neon.h:28:2: error: "NEON intrinsics not available with the soft-float ABI. Please use -mfloat-abi=softfp or -mfloat-abi=hard"
    error: metadata-generation-failed

Error installing gptme-rag.
```

Reported by @Miyou

Workaround in https://github.com/ErikBjare/gptme-rag/commit/9589856ef075cdd3ed29bd5bef87102cddb48931 by setting the max Python version to 3.12

To actually fix this we'd need to upgrade to numpy 2.0+, but it depends on ONNX fixing their numpy 2.0 support.

**Comment by ErikBjare** [comment]
At least the separation from gptme made it so that it doesn't block Python 3.13 support in gptme core

**Comment by ErikBjare** [comment]
onnxruntime now supports numpy >2.0: https://github.com/chroma-core/chroma/issues/2359

But we still need Chroma to support it, and update Chroma #3
